Repository optuna/optunahub, pull requests merged in 2024-07, with the labels that each got.

#42 Fix load settings propagation
  .github/workflows/tests.yaml
  optunahub/hub.py
  pyproject.toml
  tests/package_for_test_hub/__init__.py
  tests/package_for_test_hub/implementation.py
  tests/test_hub.py
Labels: bug

#43 Fix default value for ref
  optunahub/hub.py
Labels: bug

#45 Bump up version number to 0.1.0b0
  optunahub/version.py
Labels: other

#46 Bump up version number to `0.1.0.dev`
  optunahub/version.py
Labels: other

#44 Refactoring load module
  optunahub/hub.py
  tests/package_for_test_hub/__init__.py
  tests/test_hub.py
Labels: code-fix
