Repository optuna/optunahub, pull requests merged in 2025-06, with the labels that each got.

#97 Bump up version
  optunahub/version.py
Labels: other

#99 Fix the condition for stats report to count the default `load_module` stats
  optunahub/_conf.py
  optunahub/hub.py
  tests/test_hub.py
Labels: bug

#101 Bump up to v0.3.1
  optunahub/version.py
Labels: other

#102 Fix sampler tutorial
  recipes/001_first.py
Labels: document
